# Generated by Django 3.0.5 on 2020-05-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=64)),
                ('abstract', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('interactions', models.ManyToManyField(related_name='_protein_interactions_+', through='ppi.Interaction', to='ppi.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='frm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='ppi.Protein'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='ppi.Protein'),
        ),
    ]
